"""Crosshatch mode: Tonal Art Map hatching (Praun et al., SIGGRAPH 2001).

Authored stroke textures (resources/hatch_tam/tam_<style>/, generated by
tools/tam_generator.py) sampled by a Cycles OSL shader with custom mip
selection, so strokes keep constant SCREEN width and tone changes by adding /
removing whole strokes. This is the textured "Phase 3" of docs/hatch-tam.md;
the procedural EEVEE `hatch` mode stays untouched.

Cycles-only, CPU (OSL). Three integration facts this module encodes:

* Socket creation for Script nodes is a GUI-only operator, so the compiled
  material ships pre-built in resources/hatch_tam/tam_hatch_template.blend
  (rebuild with tools/build_crosshatch_template.py) and is APPENDED here.
  Headless Cycles recompiles the EXTERNAL .osl source at render time.
* UVs must flow through the template's UV Map node into the UVIn socket.
  The shader's getattribute(uv_name) fallback reads ZEROS in headless
  renders: Cycles only exports a mesh UV layer to the render device when a
  node requests it, and dynamic attribute names are invisible to that pass.
* Revit geometry has no UVs, so ensure_tam_uv() bakes a dominant-axis box
  projection per face into a "TamUV" layer, in world METRES (merge.py bakes
  matrix_world into merged meshes, so Object == world; the ground is NOT
  baked, hence the explicit matrix_world multiply). Hard seams land on
  architectural corners, which is where hand hatching restarts anyway.

The shader computes its own Lambert tone from the sun_dir INPUT (Cycles has
no Shader-to-RGB), and CAST SHADOWS are traced in-shader (an OSL trace()
occlusion ray toward the same direction - beyond the paper, whose tone was
orientation-only). The light DIRECTION is therefore the whole image. Default
= aim_camera_key(), a camera-relative artist's key (a site sun can backlight
a shot into flat uniform hatch - a real 21:00 spec did exactly that); Live
View's "Follow Scene Sun" toggle switches to sync_sun(), which tracks the
lamp. The synthetic ground uses a shadow_only material copy: white paper
that draws just the building's anchoring cast shadow.
"""
import math
import os

import bpy
import numpy as np
from mathutils import Vector

MATERIAL = "BIR_Crosshatch"
GROUND_MATERIAL = "BIR_CrosshatchGround"   # shadow_only=1 copy for the ground
UV_LAYER = "TamUV"
UV_VERSION = 1          # bump to force a re-bake of existing TamUV layers
STYLES = ("ink", "brush", "sketchy", "charcoal")

_RES_DIR = os.path.normpath(os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "resources", "hatch_tam"))
_TEMPLATE = os.path.join(_RES_DIR, "tam_hatch_template.blend")
_OSL = os.path.join(_RES_DIR, "tam_hatch.osl")

# Below this sun altitude the shader input is clamped: a dusk sun makes every
# face the same flat tone (hatch-flow-experiment learning). Only the shader
# input is clamped - the actual lamp (and Line Art shadows) stay site-accurate.
MIN_SUN_ALTITUDE_DEG = 20.0

# Artificial fixtures -> crosshatch tone. The nearest MAX_LIGHTS BIR_Lights
# lamps ride into the OSL shader as a packed EXR (write_light_exr); the shader
# sums their Lambert contribution into the tone so hatch lightens where lamps
# pool. GAIN maps lamp watts to the [0,1] tone range; FALLOFF is the distance
# attenuation k in 1/(1 + d2*k). Both are empirical - tune on a real interior
# (see docs/lighting.md). Kept in step with build_crosshatch_template.DEFAULTS.
MAX_LIGHTS = 64
LIGHT_GAIN = 0.02
LIGHT_FALLOFF = 0.15
_exr_serial = 0     # bump per write: a NEW path each time defeats OIIO's texture
                    # cache, so a re-gathered light set actually takes effect.


def style_dir(style):
    """Absolute tam_<style> dir with FORWARD slashes (OSL format() path)."""
    if style not in STYLES:
        style = STYLES[0]
    return os.path.join(_RES_DIR, "tam_" + style).replace("\\", "/")


def _script_node(mat):
    for n in mat.node_tree.nodes:
        if n.type == "SCRIPT":
            return n
    return None


def _script_nodes():
    """Script nodes of every crosshatch material that exists (model + ground),
    so parameter pokes and sun syncs fan out to both."""
    nodes = []
    for name in (MATERIAL, GROUND_MATERIAL):
        mat = bpy.data.materials.get(name)
        node = _script_node(mat) if mat else None
        if node is not None:
            nodes.append(node)
    return nodes


def _get_material():
    """Return the crosshatch material, appending it from the template once."""
    mat = bpy.data.materials.get(MATERIAL)
    if mat is None:
        with bpy.data.libraries.load(_TEMPLATE, link=False) as (src, dst):
            dst.materials = [m for m in src.materials if m == MATERIAL]
        mat = bpy.data.materials.get(MATERIAL)
        if mat is None:
            raise RuntimeError("material %r missing from %s" % (MATERIAL, _TEMPLATE))
        mat.use_fake_user = True
    script = _script_node(mat)
    if script is None:
        raise RuntimeError("template material lost its Script node")
    # the template stores the dev machine's path; point at THIS install's copy
    script.filepath = _OSL
    return mat


def ensure_tam_uv(objs):
    """Bake the box-projected TamUV layer on every mesh that needs it."""
    seen = set()
    for obj in objs:
        if getattr(obj, "type", None) != "MESH":
            continue
        me = obj.data
        if me is None or me in seen or len(me.polygons) == 0:
            continue
        seen.add(me)   # shared data (non-merged fallback): first user's matrix
        if me.get("bir_tam_uv_v") == UV_VERSION and me.uv_layers.get(UV_LAYER):
            continue
        _bake_box_uv(obj, me)
        me["bir_tam_uv_v"] = UV_VERSION


def _bake_box_uv(obj, me):
    nv, nl, nf = len(me.vertices), len(me.loops), len(me.polygons)
    vco = np.empty(nv * 3, dtype=np.float64)
    me.vertices.foreach_get("co", vco)
    M = np.array(obj.matrix_world)
    world = vco.reshape(nv, 3) @ M[:3, :3].T + M[:3, 3]

    li = np.empty(nl, dtype=np.int64)
    me.loops.foreach_get("vertex_index", li)
    ltot = np.empty(nf, dtype=np.int64)
    me.polygons.foreach_get("loop_total", ltot)
    fno = np.empty(nf * 3, dtype=np.float64)
    me.polygons.foreach_get("normal", fno)
    fno = fno.reshape(nf, 3) @ M[:3, :3].T

    # per-loop dominant axis of the OWNING face (np.repeat handles ngons)
    dom = np.argmax(np.abs(fno), axis=1)[np.repeat(np.arange(nf), ltot)]
    P = world[li]
    u = np.where(dom == 0, P[:, 1], P[:, 0])   # X-facing walls project (y, z)
    v = np.where(dom == 2, P[:, 1], P[:, 2])   # floors/ceilings project (x, y)

    layer = me.uv_layers.get(UV_LAYER) or me.uv_layers.new(name=UV_LAYER)
    layer.data.foreach_set("uv", np.stack([u, v], 1).astype(np.float32).ravel())


def aim_camera_key(azimuth_offset_deg=45.0, altitude_deg=45.0):
    # altitude 45: high enough that typical roof pitches don't self-shadow
    # from their own ridges under the traced cast shadows (38 left steep
    # roofs half-hatched), low enough to keep raking eave/wall shadow bands.
    """Point the shader's tone key over the camera's RIGHT shoulder (an
    artist's raking light, upper-behind). The DEFAULT tone source here.

    Tone (and the traced cast shadows) follow this direction, so a
    site-accurate sun can render a shot backlit-flat - e.g. a 21:00 spec sun
    behind the model hatched every visible face identically. The lamp itself
    contributes NOTHING to the final pixels (emission material + flat white
    world), so only the shader inputs are written; the scene sun stays
    site-accurate for every other mode. Live View's "Follow Scene Sun"
    toggle switches to sync_sun() instead. Falls back to sync_sun() when no
    camera exists."""
    nodes = _script_nodes()
    if not nodes:
        return
    cam = bpy.context.scene.camera
    if cam is None:
        sync_sun()
        return
    if cam.rotation_mode == "QUATERNION":
        q = cam.rotation_quaternion
    else:
        q = cam.rotation_euler.to_quaternion()
    f = q @ Vector((0.0, 0.0, -1.0))            # camera forward
    fh = Vector((f.x, f.y, 0.0))
    if fh.length < 1e-6:                        # straight-down 2D plan pose
        sync_sun()
        return
    back = -fh.normalized()
    ang = math.radians(azimuth_offset_deg)      # + = over the RIGHT shoulder
    side = Vector((back.x * math.cos(ang) - back.y * math.sin(ang),
                   back.x * math.sin(ang) + back.y * math.cos(ang), 0.0))
    alt = math.radians(altitude_deg)
    to_sun = Vector((side.x * math.cos(alt), side.y * math.cos(alt),
                     math.sin(alt)))
    for script in nodes:
        script.inputs["light_is_sun"].default_value = 1
        script.inputs["sun_dir"].default_value = -to_sun


def sync_sun(min_altitude_deg=MIN_SUN_ALTITUDE_DEG):
    """Push the scene sun's travel direction into the shader input.

    No-op unless both the crosshatch material and a sun lamp exist, so it is
    safe to call from the generic sun-move path for every mode."""
    nodes = _script_nodes()
    if not nodes:
        return
    from .presets import _helpers   # lazy: avoids import cycle via presets
    sun = _helpers.sun_object()
    if sun is None:
        return
    # rotation_euler, NOT matrix_world: the pipeline calls this right after
    # setup_world wrote the lamp rotation, before any depsgraph evaluation -
    # matrix_world is still identity there, which silently synced a straight-
    # DOWN sun (every wall ndl=0 -> flat mid-grey tone; roofs white).
    travel = sun.rotation_euler.to_quaternion() @ Vector((0.0, 0.0, -1.0))
    to_sun = -travel
    if to_sun.length < 1e-6:
        return
    to_sun.normalize()
    alt = math.asin(max(-1.0, min(1.0, to_sun.z)))
    floor = math.radians(min_altitude_deg)
    if alt < floor:
        az = math.atan2(to_sun.y, to_sun.x)
        to_sun = Vector((math.cos(az) * math.cos(floor),
                         math.sin(az) * math.cos(floor),
                         math.sin(floor)))
    for script in nodes:
        script.inputs["light_is_sun"].default_value = 1
        script.inputs["sun_dir"].default_value = -to_sun


def _get_ground_material():
    """Ground variant: a copy of the TAM material with shadow_only=1 - white
    paper that draws ONLY the cast shadow (the classic anchoring shadow of a
    pen drawing). A plain lit TAM on the horizontal plane under the 38-degree
    key would carpet the whole sheet in a monotone light wash instead."""
    mat = bpy.data.materials.get(GROUND_MATERIAL)
    if mat is None:
        mat = _get_material().copy()
        mat.name = GROUND_MATERIAL
        mat.use_fake_user = True
    script = _script_node(mat)
    if script is None:
        raise RuntimeError("ground material lost its Script node")
    script.filepath = _OSL
    script.inputs["shadow_only"].default_value = 1
    return mat


def apply_crosshatch(loaded, style="ink", uv_scale=0.5, ambient=0.15,
                     threshold=False):
    """Assign the shared TAM material to every model mesh; the synthetic
    ground plane gets the shadow-only variant (white paper + cast shadow).
    Real site geometry (has_site models) is model surface and hatches."""
    bpy.context.view_layer.update()   # fresh matrix_world for the UV bakes
    objs = [o for o in loaded.node_to_object.values()
            if getattr(o, "type", None) == "MESH"]
    ground = bpy.data.objects.get("BIR_Ground")
    if ground is not None and ground.type == "MESH":
        ensure_tam_uv(objs + [ground])
        ground.data.materials.clear()
        ground.data.materials.append(_get_ground_material())
    else:
        ensure_tam_uv(objs)

    mat = _get_material()
    for obj in objs:
        obj.data.materials.clear()
        obj.data.materials.append(mat)
    set_crosshatch(style=style, uv_scale=uv_scale, ambient=ambient,
                   threshold=threshold)
    aim_camera_key()
    # Seed the fixture sockets to a known OFF state (n_lights 0). Crosshatch
    # defaults to no artificial-light contribution - the interior look is opt-in
    # via Live View's "Artificial Lights" toggle (through-wall bleed makes it a
    # poor default for the common exterior shot). refresh_lights below flips it.
    refresh_lights(strength=1.0, enabled=False)
    return mat


def set_crosshatch(style=None, uv_scale=None, ambient=None, threshold=None,
                   shadows=None):
    """Live update: poke script inputs in place (no rebuild, no retrace).
    Fans out to the ground variant so both stay in step."""
    for script in _script_nodes():
        if style is not None:
            script.inputs["tam_dir"].default_value = style_dir(str(style))
        if uv_scale is not None:
            script.inputs["uv_scale"].default_value = float(uv_scale)
        if ambient is not None:
            script.inputs["ambient"].default_value = float(ambient)
        if threshold is not None:
            script.inputs["threshold"].default_value = int(bool(threshold))
        if shadows is not None:
            script.inputs["cast_shadows"].default_value = int(bool(shadows))


# --- artificial fixtures drive the hatch tone -------------------------------
def _set_input(script, name, value):
    """Poke a script socket if it exists. Guarded so refresh_lights is a no-op
    against a stale template that predates the light sockets (the Python lands
    safely before build_crosshatch_template.py is re-run)."""
    sock = script.inputs.get(name)
    if sock is not None:
        sock.default_value = value


def _lamp_world(obj):
    """(position, spot-aim | None, energy watts, cos(field half), cos(beam half))
    for a BIR_Lights lamp, read straight off its world matrix (already metres)."""
    from mathutils import Vector
    mw = obj.matrix_world
    pos = mw.translation
    data = obj.data
    # UNSCALED base watts: Live's "Lights Strength" scales data.energy for the
    # lit modes (set_lights_strength stashes bir_base_watts); here that slider
    # instead drives light_gain, so read the base to avoid double-counting.
    watts = obj.get("bir_base_watts", getattr(data, "energy", 0.0))
    aim = None
    cos_outer, cos_inner = -1.0, 1.0
    if getattr(data, "type", "") == "SPOT":
        aim = (mw.to_quaternion() @ Vector((0.0, 0.0, -1.0))).normalized()
        half_field = min(math.radians(89.5),
                         float(getattr(data, "spot_size", math.pi * 0.5)) * 0.5)
        blend = max(0.0, min(1.0, float(getattr(data, "spot_blend", 0.15))))
        half_beam = half_field * (1.0 - blend)
        cos_outer = math.cos(half_field)
        cos_inner = math.cos(half_beam)
    return pos, aim, float(watts), cos_outer, cos_inner


def write_light_exr(cam_loc):
    """Gather BIR_Lights, keep the MAX_LIGHTS nearest cam_loc, write a packed
    float EXR (1 row x 3*N cols, RGB) into the session tempdir. Returns
    (forward-slash path, count); ("", 0) when there are no fixtures.

    Width-packing (not rows) sidesteps any vertical-flip ambiguity: the shader
    reads all three texels of light i at v=0.5, columns 3i..3i+2. Callers MUST
    have the lamp transforms evaluated (view_layer.update) before this reads
    obj.matrix_world - a stale identity matrix packs every lamp at the origin.

    The nearest-N cull is re-run per camera (like aim_camera_key) so a big Revit
    model with hundreds of fixtures only ever ships the lamps around the shot."""
    global _exr_serial
    coll = bpy.data.collections.get("BIR_Lights")
    lamps = [o for o in (coll.objects if coll else []) if getattr(o, "data", None)]
    if not lamps:
        return "", 0
    cam = Vector(cam_loc)
    lamps.sort(key=lambda o: (o.matrix_world.translation - cam).length_squared)
    lamps = lamps[:MAX_LIGHTS]
    n = len(lamps)

    buf = np.zeros((n * 3, 4), dtype=np.float32)   # Blender image px are RGBA
    for i, o in enumerate(lamps):
        pos, aim, watts, co, ci = _lamp_world(o)
        buf[3 * i, 0:3] = (pos.x, pos.y, pos.z)
        if aim is not None:
            buf[3 * i + 1, 0:3] = (aim.x, aim.y, aim.z)
        buf[3 * i + 2, 0:3] = (watts, co, ci)
    buf[:, 3] = 1.0

    img = bpy.data.images.new("BIR_LightData", width=n * 3, height=1,
                              float_buffer=True, alpha=False)
    try:
        # Non-Color BEFORE foreach_set: assigning the colorspace AFTER the pixel
        # write re-derives the buffer through the scene's view transform and, in
        # a Standard-view scene (crosshatch uses set_flat_view), ZEROED the RGB
        # while alpha survived - the packed positions came back (0,0,0).
        img.colorspace_settings.name = "Non-Color"   # raw data, no view xform
        img.pixels.foreach_set(buf.ravel())
        _exr_serial += 1
        path = os.path.join(bpy.app.tempdir, "bir_lightdata_%d.exr" % _exr_serial)
        img.filepath_raw = path
        img.file_format = "OPEN_EXR"
        img.save()
    finally:
        bpy.data.images.remove(img)   # the .exr on disk persists; drop the block
    return path.replace("\\", "/"), n


def refresh_lights(strength=1.0, enabled=True):
    """(Re)write the light-data EXR from the current scene camera and poke the
    crosshatch material's fixture sockets. No-op when no crosshatch material
    exists. n_lights=0 (shader skips the loop) when disabled or no fixtures.

    The shadow_only ground material also receives the sockets, but its shader
    branch never runs the fixture loop, so lamps never paint the paper."""
    nodes = _script_nodes()
    if not nodes:
        return
    path, count = "", 0
    if enabled:
        cam = bpy.context.scene.camera
        loc = cam.matrix_world.translation if cam is not None else (0.0, 0.0, 0.0)
        path, count = write_light_exr(loc)
    gain = LIGHT_GAIN * (1.0 if strength is None else float(strength))
    for script in nodes:
        _set_input(script, "light_data", path)
        _set_input(script, "n_lights", int(count))
        _set_input(script, "light_gain", float(gain))
        _set_input(script, "light_falloff", float(LIGHT_FALLOFF))
