"""Crosshatch mode: Tonal Art Map hatching (Praun et al., SIGGRAPH 2001).

Authored stroke textures (resources/hatch_tam/tam_<style>/, generated by
tools/tam_generator.py) sampled by a Cycles OSL shader with custom mip
selection, so strokes keep constant SCREEN width and tone changes by adding /
removing whole strokes. This is the textured "Phase 3" of docs/hatch-tam.md;
the procedural EEVEE `hatch` mode stays untouched.

Cycles-only, CPU (OSL). Three integration facts this module encodes:

* Socket creation for Script nodes is a GUI-only operator, so the compiled
  material ships pre-built in resources/hatch_tam/tam_hatch_template.blend
  (rebuild with tools/build_crosshatch_template.py) and is APPENDED here.
  Headless Cycles recompiles the EXTERNAL .osl source at render time.
* UVs must flow through the template's UV Map node into the UVIn socket.
  The shader's getattribute(uv_name) fallback reads ZEROS in headless
  renders: Cycles only exports a mesh UV layer to the render device when a
  node requests it, and dynamic attribute names are invisible to that pass.
* Revit geometry has no UVs, so ensure_tam_uv() bakes a dominant-axis box
  projection per face into a "TamUV" layer, in world METRES (merge.py bakes
  matrix_world into merged meshes, so Object == world; the ground is NOT
  baked, hence the explicit matrix_world multiply). Hard seams land on
  architectural corners, which is where hand hatching restarts anyway.

The shader computes its own Lambert tone from the sun_dir INPUT (Cycles has
no Shader-to-RGB). Tone is orientation-only - no cast shadows, no AO
(faithful to the paper; unlike `hatch`, where the shadows are the drawing) -
so the light DIRECTION is the whole image. Default = aim_camera_key(), a
camera-relative artist's key (a site sun can backlight a shot into flat
uniform hatch - a real 21:00 spec did exactly that); Live View's "Follow
scene sun" toggle switches to sync_sun(), which tracks the lamp.
"""
import math
import os

import bpy
import numpy as np
from mathutils import Vector

MATERIAL = "BIR_Crosshatch"
UV_LAYER = "TamUV"
UV_VERSION = 1          # bump to force a re-bake of existing TamUV layers
STYLES = ("ink", "brush", "sketchy", "charcoal")

_RES_DIR = os.path.normpath(os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "resources", "hatch_tam"))
_TEMPLATE = os.path.join(_RES_DIR, "tam_hatch_template.blend")
_OSL = os.path.join(_RES_DIR, "tam_hatch.osl")

# Below this sun altitude the shader input is clamped: a dusk sun makes every
# face the same flat tone (hatch-flow-experiment learning). Only the shader
# input is clamped - the actual lamp (and Line Art shadows) stay site-accurate.
MIN_SUN_ALTITUDE_DEG = 20.0


def style_dir(style):
    """Absolute tam_<style> dir with FORWARD slashes (OSL format() path)."""
    if style not in STYLES:
        style = STYLES[0]
    return os.path.join(_RES_DIR, "tam_" + style).replace("\\", "/")


def _script_node(mat):
    for n in mat.node_tree.nodes:
        if n.type == "SCRIPT":
            return n
    return None


def _get_material():
    """Return the crosshatch material, appending it from the template once."""
    mat = bpy.data.materials.get(MATERIAL)
    if mat is None:
        with bpy.data.libraries.load(_TEMPLATE, link=False) as (src, dst):
            dst.materials = [m for m in src.materials if m == MATERIAL]
        mat = bpy.data.materials.get(MATERIAL)
        if mat is None:
            raise RuntimeError("material %r missing from %s" % (MATERIAL, _TEMPLATE))
        mat.use_fake_user = True
    script = _script_node(mat)
    if script is None:
        raise RuntimeError("template material lost its Script node")
    # the template stores the dev machine's path; point at THIS install's copy
    script.filepath = _OSL
    return mat


def ensure_tam_uv(objs):
    """Bake the box-projected TamUV layer on every mesh that needs it."""
    seen = set()
    for obj in objs:
        if getattr(obj, "type", None) != "MESH":
            continue
        me = obj.data
        if me is None or me in seen or len(me.polygons) == 0:
            continue
        seen.add(me)   # shared data (non-merged fallback): first user's matrix
        if me.get("bir_tam_uv_v") == UV_VERSION and me.uv_layers.get(UV_LAYER):
            continue
        _bake_box_uv(obj, me)
        me["bir_tam_uv_v"] = UV_VERSION


def _bake_box_uv(obj, me):
    nv, nl, nf = len(me.vertices), len(me.loops), len(me.polygons)
    vco = np.empty(nv * 3, dtype=np.float64)
    me.vertices.foreach_get("co", vco)
    M = np.array(obj.matrix_world)
    world = vco.reshape(nv, 3) @ M[:3, :3].T + M[:3, 3]

    li = np.empty(nl, dtype=np.int64)
    me.loops.foreach_get("vertex_index", li)
    ltot = np.empty(nf, dtype=np.int64)
    me.polygons.foreach_get("loop_total", ltot)
    fno = np.empty(nf * 3, dtype=np.float64)
    me.polygons.foreach_get("normal", fno)
    fno = fno.reshape(nf, 3) @ M[:3, :3].T

    # per-loop dominant axis of the OWNING face (np.repeat handles ngons)
    dom = np.argmax(np.abs(fno), axis=1)[np.repeat(np.arange(nf), ltot)]
    P = world[li]
    u = np.where(dom == 0, P[:, 1], P[:, 0])   # X-facing walls project (y, z)
    v = np.where(dom == 2, P[:, 1], P[:, 2])   # floors/ceilings project (x, y)

    layer = me.uv_layers.get(UV_LAYER) or me.uv_layers.new(name=UV_LAYER)
    layer.data.foreach_set("uv", np.stack([u, v], 1).astype(np.float32).ravel())


def aim_camera_key(azimuth_offset_deg=45.0, altitude_deg=38.0):
    """Point the shader's tone key over the camera's shoulder (classic artist
    light: upper-left-behind). The DEFAULT tone source for this mode.

    Tone is the entire image here (no cast shadows), so a site-accurate sun
    can render a shot backlit-flat - e.g. a 21:00 spec sun behind the model
    hatched every visible face identically. The lamp itself contributes
    NOTHING to the final pixels (emission material + flat white world), so
    only the shader input is written; the scene sun stays site-accurate for
    every other mode. Live View's "Follow scene sun" toggle switches to
    sync_sun() instead. Falls back to sync_sun() when no camera exists."""
    mat = bpy.data.materials.get(MATERIAL)
    script = _script_node(mat) if mat else None
    if script is None:
        return
    cam = bpy.context.scene.camera
    if cam is None:
        sync_sun()
        return
    if cam.rotation_mode == "QUATERNION":
        q = cam.rotation_quaternion
    else:
        q = cam.rotation_euler.to_quaternion()
    f = q @ Vector((0.0, 0.0, -1.0))            # camera forward
    fh = Vector((f.x, f.y, 0.0))
    if fh.length < 1e-6:                        # straight-down 2D plan pose
        sync_sun()
        return
    back = -fh.normalized()
    ang = math.radians(azimuth_offset_deg)      # + = over the LEFT shoulder
    left = Vector((back.x * math.cos(ang) - back.y * math.sin(ang),
                   back.x * math.sin(ang) + back.y * math.cos(ang), 0.0))
    alt = math.radians(altitude_deg)
    to_sun = Vector((left.x * math.cos(alt), left.y * math.cos(alt),
                     math.sin(alt)))
    script.inputs["light_is_sun"].default_value = 1
    script.inputs["sun_dir"].default_value = -to_sun


def sync_sun(min_altitude_deg=MIN_SUN_ALTITUDE_DEG):
    """Push the scene sun's travel direction into the shader input.

    No-op unless both the crosshatch material and a sun lamp exist, so it is
    safe to call from the generic sun-move path for every mode."""
    mat = bpy.data.materials.get(MATERIAL)
    script = _script_node(mat) if mat else None
    if script is None:
        return
    from .presets import _helpers   # lazy: avoids import cycle via presets
    sun = _helpers.sun_object()
    if sun is None:
        return
    # rotation_euler, NOT matrix_world: the pipeline calls this right after
    # setup_world wrote the lamp rotation, before any depsgraph evaluation -
    # matrix_world is still identity there, which silently synced a straight-
    # DOWN sun (every wall ndl=0 -> flat mid-grey tone; roofs white).
    travel = sun.rotation_euler.to_quaternion() @ Vector((0.0, 0.0, -1.0))
    to_sun = -travel
    if to_sun.length < 1e-6:
        return
    to_sun.normalize()
    alt = math.asin(max(-1.0, min(1.0, to_sun.z)))
    floor = math.radians(min_altitude_deg)
    if alt < floor:
        az = math.atan2(to_sun.y, to_sun.x)
        to_sun = Vector((math.cos(az) * math.cos(floor),
                         math.sin(az) * math.cos(floor),
                         math.sin(floor)))
    script.inputs["light_is_sun"].default_value = 1
    script.inputs["sun_dir"].default_value = -to_sun


PAPER_MATERIAL = "BIR_CrosshatchPaper"


def _paper_material():
    mat = bpy.data.materials.get(PAPER_MATERIAL)
    if mat is None:
        from . import npr
        mat = npr.make_flat_material((1.0, 1.0, 1.0), name=PAPER_MATERIAL)
    return mat


def apply_crosshatch(loaded, style="ink", uv_scale=0.5, ambient=0.15,
                     threshold=False):
    """Assign the ONE shared TAM material to every model mesh. The synthetic
    ground plane stays WHITE PAPER instead: it's scenography, not model - a
    horizontal plane under the 38-degree key would otherwise carpet the whole
    sheet in a monotone light wash (there are no cast shadows to draw on it).
    Real site geometry (has_site models) is model surface and hatches."""
    objs = [o for o in loaded.node_to_object.values()
            if getattr(o, "type", None) == "MESH"]
    ensure_tam_uv(objs)

    mat = _get_material()
    for obj in objs:
        obj.data.materials.clear()
        obj.data.materials.append(mat)
    ground = bpy.data.objects.get("BIR_Ground")
    if ground is not None and ground.type == "MESH":
        ground.data.materials.clear()
        ground.data.materials.append(_paper_material())
    set_crosshatch(style=style, uv_scale=uv_scale, ambient=ambient,
                   threshold=threshold)
    aim_camera_key()
    return mat


def set_crosshatch(style=None, uv_scale=None, ambient=None, threshold=None):
    """Live update: poke script inputs in place (no rebuild, no retrace)."""
    mat = bpy.data.materials.get(MATERIAL)
    script = _script_node(mat) if mat else None
    if script is None:
        return
    if style is not None:
        script.inputs["tam_dir"].default_value = style_dir(str(style))
    if uv_scale is not None:
        script.inputs["uv_scale"].default_value = float(uv_scale)
    if ambient is not None:
        script.inputs["ambient"].default_value = float(ambient)
    if threshold is not None:
        script.inputs["threshold"].default_value = int(bool(threshold))
